# Generated by Django 3.0.6 on 2020-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_tweet_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='deadpool.jpeg', upload_to='profile_pics'),
        ),
    ]
